name: CI
on:
  pull_request:
    branches:
      - release/*
      - main
    types:
      - opened
      - reopened
      - edited
      - synchronized
  push:
    branches:
      - release/*
      - main
      - feature/*

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install node dependencies
        run: npm ci
      - name: check formatting
        run: |
          npm run format:check
      - name: Build Artifact - Maven
        run: |
          mvn clean package -DskipTests=true
      # - name: cache dependencies  todo: investigate where maven store dependencies
      - name: Unit Tests
        run: |
          mvn test
          ls ./target/surefire-reports/*.xml

      - name: upload test report Artifact
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: test-report
          path: ./target/surefire-reports/*.xml # or path/to/artifact

      - name: upload main Artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: target/*.jar # or path/to/artifact

      # Docker buld and push
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/numeric-app:${{ github.sha }}

  deploy_to_dev:
    runs-on: ubuntu-latest
    needs:
      - ci
    steps:
      - uses: actions/checkout@v3

      # install kubectl
      - uses: azure/setup-kubectl@v2.0

      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: ${{ secrets.KUBERNETES_URL }}
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}

      - name: replace image value
        working-directory: ./manifests
        run: |
          sed -i 's#replace#${{ secrets.DOCKER_HUB_USERNAME }}/numeric-app:${{ github.sha }}#g' k8s_deployment_service.yaml

      # deploy
      - uses: Azure/k8s-deploy@v3.1
        with:
          action: deploy
          manifests: |
            manifests/k8s_deployment_service.yaml
          